const statesWithTaxList = [
    { name: "Alabama", taxRate: 0.04 },
    { name: "Alaska", taxRate: 0.0 },
    { name: "Arizona", taxRate: 0.056 },
    { name: "Arkansas", taxRate: 0.065 },
    { name: "California", taxRate: 0.0725 },
    { name: "Colorado", taxRate: 0.029 },
    { name: "Connecticut", taxRate: 0.0635 },
    { name: "Delaware", taxRate: 0.0 },
    { name: "Florida", taxRate: 0.06 },
    { name: "Georgia", taxRate: 0.04 },
    { name: "Hawaii", taxRate: 0.04 },
    { name: "Idaho", taxRate: 0.06 },
    { name: "Illinois", taxRate: 0.0625 },
    { name: "Indiana", taxRate: 0.07 },
    { name: "Iowa", taxRate: 0.06 },
    { name: "Kansas", taxRate: 0.065 },
    { name: "Kentucky", taxRate: 0.06 },
    { name: "Louisiana", taxRate: 0.0445 },
    { name: "Maine", taxRate: 0.055 },
    { name: "Maryland", taxRate: 0.06 },
    { name: "Massachusetts", taxRate: 0.0625 },
    { name: "Michigan", taxRate: 0.06 },
    { name: "Minnesota", taxRate: 0.06875 },
    { name: "Mississippi", taxRate: 0.07 },
    { name: "Missouri", taxRate: 0.04225 },
    { name: "Montana", taxRate: 0.0 },
    { name: "Nebraska", taxRate: 0.055 },
    { name: "Nevada", taxRate: 0.0685 },
    { name: "New Hampshire", taxRate: 0.0 },
    { name: "New Jersey", taxRate: 0.06625 },
    { name: "New Mexico", taxRate: 0.05125 },
    { name: "New York", taxRate: 0.04 },
    { name: "North Carolina", taxRate: 0.0475 },
    { name: "North Dakota", taxRate: 0.05 },
    { name: "Ohio", taxRate: 0.0575 },
    { name: "Oklahoma", taxRate: 0.045 },
    { name: "Oregon", taxRate: 0.0 },
    { name: "Pennsylvania", taxRate: 0.06 },
    { name: "Rhode Island", taxRate: 0.07 },
    { name: "South Carolina", taxRate: 0.06 },
    { name: "South Dakota", taxRate: 0.045 },
    { name: "Tennessee", taxRate: 0.07 },
    { name: "Texas", taxRate: 0.0625 },
    { name: "Utah", taxRate: 0.0595 },
    { name: "Vermont", taxRate: 0.06 },
    { name: "Virginia", taxRate: 0.053 },
    { name: "Washington", taxRate: 0.065 },
    { name: "West Virginia", taxRate: 0.06 },
    { name: "Wisconsin", taxRate: 0.05 },
    { name: "Wyoming", taxRate: 0.04 }
];

export default statesWithTaxList;
